POST http://localhost:8787/webhook HTTP/1.1
Content-Type: application/json
X-Payjp-Webhook-Token: whook_1234567890abcdef

{
  "type": "subscription.renewed",
  "description": "定期課金の期間が更新されました",
  "livemode": false,
  "object": "event",
  "id": "evnt_xxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "data": {
      "id": "sub_xxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "plan": {
          "id": "test-gatchan-ai-premium",
          "name": "がっちゃんAIのプレミアムプラン",
          "amount": 500,
          "object": "plan",
          "created": 1733922919,
          "currency": "jpy",
          "interval": "month",
          "livemode": false,
          "metadata": {},
          "trial_days": 14,
          "billing_day": 25
      },
      "start": 1734504396,
      "object": "subscription",
      "status": "active",
      "created": 1734504396,
      "prorate": false,
      "customer": "cus_xxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "livemode": false,
      "metadata": {},
      "paused_at": null,
      "trial_end": 1735713996,
      "resumed_at": null,
      "canceled_at": null,
      "trial_start": 1734504396,
      "next_cycle_plan": null,
      "current_period_end": 1737763236,
      "current_period_start": 1735713996
  },
  "pending_webhooks": 0,
  "created": 1735714225
}