POST http://localhost:8787/webhook HTTP/1.1
Content-Type: application/json
X-Payjp-Webhook-Token: whook_1234567890abcdef

{
  "type": "subscription.created",
  "livemode": false,
  "object": "event",
  "id": "evnt_xxxxxxxxxxxxxxxxxxxxxxxx",
  "pending_webhooks": 1,
  "created": 1735785953,
  "data": {
    "plan": {
      "metadata": {},
      "livemode": false,
      "id": "test-gatchan-ai-premium",
      "name": "がっちゃんAIのプレミアムプラン",
      "object": "plan",
      "currency": "jpy",
      "interval": "month",
      "amount": 500,
      "created": 1733922919,
      "trial_days": 14,
      "billing_day": 25
    },
    "metadata": {},
    "prorate": false,
    "livemode": false,
    "id": "sub_xxxxxxxxxxxxxxxxxxxxxxxx",
    "object": "subscription",
    "status": "trial",
    "customer": "cus_xxxxxxxxxxxxxxxxxxxxxxxx",
    "start": 1735785953,
    "created": 1735785953,
    "trial_end": 1736995553,
    "trial_start": 1735785953,
    "current_period_end": 1736995553,
    "current_period_start": 1735785953
  }
}