CREATE TABLE cards (
    id TEXT PRIMARY KEY,
    name TEXT,
    brand TEXT,
    email TEXT,
    last4 TEXT,
    phone TEXT,
    object TEXT,
    country TEXT,
    created INTEGER,
    customer TEXT,
    exp_year INTEGER,
    livemode BOOLEAN,
    cvc_check TEXT,
    exp_month INTEGER,
    address_zip TEXT,
    fingerprint TEXT,
    address_city TEXT,
    address_line1 TEXT,
    address_line2 TEXT,
    address_state TEXT,
    address_zip_check TEXT,
    three_d_secure_status TEXT
);